main: pl.auroramc.essentials.EssentialsBukkitPlugin
name: auroramc-essentials
version: ${project.version}-${git.commit.id.abbrev}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - org.mariadb.jdbc:mariadb-java-client:3.3.3