main: pl.auroramc.essentials.EssentialsBukkitPlugin
name: auroramc-essentials
version: ${project.version}-${git.commit.id.abbrev}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
libraries:
  - it.unimi.dsi:sux4j:5.4.1
  - com.github.ben-manes.caffeine:caffeine:3.1.8
