main: pl.auroramc.scoreboard.ScoreboardBukkitPlugin
name: auroramc-scoreboard
version: ${project.version}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
depend:
  - PlaceholderAPI
softdepend:
  - auroramc-registry
  - auroramc-quests
libraries:
  - fr.mrmicky:fastboard:2.1.0
  - com.github.ben-manes.caffeine:caffeine:3.1.8