main: pl.auroramc.auctions.AuctionsBukkitPlugin
name: auroramc-auctions
version: ${project.version}-${git.commit.id.abbrev}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
depend:
  - auroramc-registry
  - auroramc-economy
libraries:
  - org.mariadb.jdbc:mariadb-java-client:3.3.3
  - com.spotify:completable-futures:0.3.6
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - com.github.stefvanschie.inventoryframework:IF:0.10.13