main: pl.auroramc.cheque.ChequeBukkitPlugin
name: auroramc-cheque
version: ${project.version}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
depend:
  - auroramc-registry
  - auroramc-economy
libraries:
  - org.mariadb.jdbc:mariadb-java-client:3.3.3
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - com.spotify:completable-futures:0.3.6