main: pl.auroramc.cheque.ChequeBukkitPlugin
name: auroramc-cheque
version: ${project.version}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
depend:
  - auroramc-registry
  - auroramc-economy