main: pl.auroramc.gamble.GambleBukkitPlugin
name: auroramc-gamble
version: ${project.version}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
depend:
  - auroramc-economy
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8