main: pl.auroramc.shops.ShopsBukkitPlugin
name: auroramc-shops
version: ${project.version}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
depend:
  - auroramc-economy
libraries:
  - org.apache.groovy:groovy-jsr223:5.0.0-alpha-7
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - com.github.stefvanschie.inventoryframework:IF:0.10.13