main: pl.auroramc.registry.RegistryBukkitPlugin
name: auroramc-registry
version: ${project.version}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8
