main: pl.auroramc.registry.RegistryBukkitPlugin
name: auroramc-registry
version: ${project.version}-${git.commit.id.abbrev}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
libraries:
  - org.mariadb.jdbc:mariadb-java-client:3.3.3
  - com.github.ben-manes.caffeine:caffeine:3.1.8
