main: pl.auroramc.economy.EconomyBukkitPlugin
name: auroramc-economy
version: ${project.version}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
depend:
  - auroramc-registry
softdepend:
  - PlaceholderAPI
libraries:
  - io.javalin:javalin:6.1.3
  - com.spotify:completable-futures:0.3.6
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - com.fasterxml.jackson.core:jackson-databind:2.17.0