main: pl.auroramc.lobby.LobbyBukkitPlugin
name: auroramc-lobby
version: ${project.version}-${git.commit.id.abbrev}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8