main: pl.auroramc.bazaars.BazaarsBukkitPlugin
name: auroramc-bazaars
version: ${project.version}
authors: [ shitzuu <hello@rafal.moe ]
api-version: 1.20
depend:
  - auroramc-registry
  - auroramc-economy