main: pl.auroramc.bazaars.BazaarsBukkitPlugin
name: auroramc-bazaars
version: ${project.version}-${git.commit.id.abbrev}
authors: [ shitzuu <hello@rafal.moe ]
api-version: 1.20
depend:
  - auroramc-registry
  - auroramc-economy
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8