main: pl.auroramc.bounty.BountyBukkitPlugin
name: auroramc-bounty
version: ${project.version}-${git.commit.id.abbrev}
authors: [ shitzuu <hello@rafal.moe> ]
api-version: 1.20
depend:
  - auroramc-registry
libraries:
  - org.apache.groovy:groovy-jsr223:5.0.0-alpha-7
  - org.mariadb.jdbc:mariadb-java-client:3.3.3
  - com.github.ben-manes.caffeine:caffeine:3.1.8